name:                tracnologia
version:             0.1.0.0
github:              "githubuser/tracnologia"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tracnologia#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- attoparsec
- bytestring
- casing
- esqueleto
- hpqtypes
- http-api-data
- http-media
- http-types
- lens
- monad-logger
- mtl
- persistent
- persistent-postgresql
- persistent-template
- servant
- servant-auth
- servant-auth-server
- servant-checked-exceptions
- servant-js
- servant-server
- scrypt
- template-haskell
- text
- time
- transformers
- tuple
- tuples-homogenous-h98
- wai-cors
- wai-extra
- warp
- warp-tls
- tz

library:
  source-dirs: src

executables:
  tracnologia-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tracnologia

tests:
  tracnologia-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tracnologia
